name: Publish Website

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "[1-9]+.[0-9]+.[0-9]+"
  create:
    branches-ignore:
      - "*"
    tags:
      - "[1-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build CDN assets
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [12.x, 14.x, 16.x]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    name: Deploy CDN assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDN assets to S3 + CloudFront
        run: |
          aws s3 rm --recursive ${{ secrets.AWS_S3_BUCKET }}pedal/
          aws s3 cp --recursive build ${{ secrets.AWS_S3_BUCKET }}pedal/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PDDYRDBRD_CDN }} --paths "/pedal/*"

