name: Publish Website

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "[1-9]+.[0-9]+.[0-9]+"
  create:
    branches-ignore:
      - "*"
    tags:
      - "[1-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy CDN assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDN assets to S3 + CloudFront
        run: |
          aws s3 cp --recursive public ${{ secrets.AWS_S3_BUCKET }}pedal/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PDDYRDBRD_CDN }} --paths "/pedal/*"

